---
- name: Reload systemctl
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"
- name: Restart collectd service
  service: name=collectd state=restarted enabled=yes
  when: ansible_service_mgr == "systemd"
- name: Restart collectd service
  shell: service collectd restarted
  when: ansible_service_mgr == "upstart"
